[package]
name = "recall_api"
version = "0.1.0"
authors = ["Eric Reichert <eric@reichertconsulting.com>"]
edition = "2018"

[dependencies]
diesel = { version = "1.4.5", features = ["postgres"] }
dotenv = "0.15.0"